In [2]:
import numpy as np

def frame_element_stiffness(E, A, I, L):
    """
    Çerçeve elemanı için yerel rijitlik matrisi oluşturur.
    """
    k_local = np.array([
        [E*A/L,      0,          0,        -E*A/L,      0,          0],
        [0,      12*E*I/L**3,  6*E*I/L**2,  0,      -12*E*I/L**3, 6*E*I/L**2],
        [0,      6*E*I/L**2,   4*E*I/L,    0,      -6*E*I/L**2,   2*E*I/L],
        [-E*A/L,   0,          0,         E*A/L,      0,          0],
        [0,     -12*E*I/L**3, -6*E*I/L**2, 0,       12*E*I/L**3, -6*E*I/L**2],
        [0,      6*E*I/L**2,   2*E*I/L,    0,      -6*E*I/L**2,   4*E*I/L]
    ])
    return k_local

def rotation_matrix(theta):
    """
    Rotasyon matrisini oluşturur.
    """
    c = np.cos(theta)
    s = np.sin(theta)

    T = np.array([
        [ c,  s,  0,  0,  0,  0],
        [-s,  c,  0,  0,  0,  0],
        [ 0,  0,  1,  0,  0,  0],
        [ 0,  0,  0,  c,  s,  0],
        [ 0,  0,  0, -s,  c,  0],
        [ 0,  0,  0,  0,  0,  1]
    ])
    return T

def global_stiffness(k_local, T):
    """
    Yerel rijitlik matrisini küresel koordinatlara dönüştürür.
    """
    T_transpose = T.T
    k_global = T_transpose @ k_local @ T
    return k_global

# Kullanıcıdan giriş alalım
def user_input():
    print("Çerçeve Elemanı İçin Küresel Rijitlik Matrisi Hesaplama")
    E = float(input("Elastisite Modülü (E) [Pa]: "))
    A = float(input("Kesit Alanı (A) [m^2]: "))
    I = float(input("Atalet Momenti (I) [m^4]: "))
    L = float(input("Eleman Uzunluğu (L) [m]: "))
    theta_deg = float(input("Eleman Açısı (θ) [derece]: "))
    theta_rad = np.radians(theta_deg)  # Dereceyi radyana çevir
    return E, A, I, L, theta_rad

# Ana program
if __name__ == "__main__":
    # Kullanıcıdan parametreleri al
    E, A, I, L, theta = user_input()

    # Yerel rijitlik matrisini hesapla
    k_local = frame_element_stiffness(E, A, I, L)

    # Rotasyon matrisini hesapla
    T = rotation_matrix(theta)

    # Küresel rijitlik matrisini hesapla
    k_global = global_stiffness(k_local, T)

    # Sonuçları göster
    print("\nYerel Rijitlik Matrisi (k_local):\n")
    print(np.round(k_local, 3))

    print("\nRotasyon Matrisi (T):\n")
    print(np.round(T, 3))

    print("\nKüresel Rijitlik Matrisi (k_global):\n")
    print(np.round(k_global, 3))


Çerçeve Elemanı İçin Küresel Rijitlik Matrisi Hesaplama
Elastisite Modülü (E) [Pa]: 1
Kesit Alanı (A) [m^2]: 1
Atalet Momenti (I) [m^4]: 1
Eleman Uzunluğu (L) [m]: 5
Eleman Açısı (θ) [derece]: 323

Yerel Rijitlik Matrisi (k_local):

[[ 0.2    0.     0.    -0.2    0.     0.   ]
 [ 0.     0.096  0.24   0.    -0.096  0.24 ]
 [ 0.     0.24   0.8    0.    -0.24   0.4  ]
 [-0.2    0.     0.     0.2    0.     0.   ]
 [ 0.    -0.096 -0.24   0.     0.096 -0.24 ]
 [ 0.     0.24   0.4    0.    -0.24   0.8  ]]

Rotasyon Matrisi (T):

[[ 0.799 -0.602  0.     0.     0.     0.   ]
 [ 0.602  0.799  0.     0.     0.     0.   ]
 [ 0.     0.     1.     0.     0.     0.   ]
 [ 0.     0.     0.     0.799 -0.602  0.   ]
 [ 0.     0.     0.     0.602  0.799  0.   ]
 [ 0.     0.     0.     0.     0.     1.   ]]

Küresel Rijitlik Matrisi (k_global):

[[ 0.162 -0.05   0.144 -0.162  0.05   0.144]
 [-0.05   0.134  0.192  0.05  -0.134  0.192]
 [ 0.144  0.192  0.8   -0.144 -0.192  0.4  ]
 [-0.162  0.05  -0.144  0.1

In [5]:
A = np.array([
    [0],
    [0],
    [0],
    [0],
    [27.22],
    [33.56]])
dLA = T @ A
dLA

array([[  0.        ],
       [  0.        ],
       [  0.        ],
       [-16.38140493],
       [ 21.73885858],
       [ 33.56      ]])

In [6]:
fL6_ = k_local@dLA
fL6_

array([[ 3.27628099],
       [ 5.96746958],
       [ 8.20667394],
       [-3.27628099],
       [-5.96746958],
       [21.63067394]])

In [7]:
fem_ce = np.array(
    [[0],
    [20],
    [25],
    [0],
    [20],
    [-25]])

fLce = fL6_ + fem_ce
print(fLce)

[[ 3.27628099]
 [25.96746958]
 [33.20667394]
 [-3.27628099]
 [14.03253042]
 [-3.36932606]]
